version: 0.9.0-{branch}-{build}
os: Windows Server 2012 R2
build_script:
- build_appvoyer.cmd
test: off
artifacts:
- path: package-results/release/*.nupkg
  name: NuGet Packages
on_finish:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results\ConfigurationMapper.UnitTests.CoreCLR.xml))

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results\ConfigurationMapper.IntegrationTests.CoreCLR.xml))

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results\ConfigurationMapper.UnitTests.CLR.xml))

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results\ConfigurationMapper.IntegrationTests.CLR.xml))